//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auspiciador
    {
        public int id_auspiciador { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string url_logo { get; set; }
    }
}
