//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplina
    {
        public int id_disciplina { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    }
}
