//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadistica
    {
        public int id_estadistica { get; set; }
        public string pos_manga1 { get; set; }
        public string pos_manga2 { get; set; }
        public string pos_final { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
