//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int id_evento { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string fecha { get; set; }
        public string url_flayer { get; set; }
        public string descripcion { get; set; }
        public int id_disciplina { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Estadistica Estadistica { get; set; }
    }
}
