//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int id_evento { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string fecha { get; set; }
        public string url_flayer { get; set; }
    }
}
