//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaniaEntitiesContainer : DbContext
    {
        public TaniaEntitiesContainer()
            : base("name=TaniaEntitiesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Foto> Fotos { get; set; }
        public DbSet<Evento> Eventos { get; set; }
        public DbSet<Auspiciador> Auspiciadores { get; set; }
        public DbSet<Disciplina> Disciplinas { get; set; }
        public DbSet<Logro> Logros { get; set; }
        public DbSet<Categoria> Categorias { get; set; }
        public DbSet<Reporte> Reportes { get; set; }
        public DbSet<Estadistica> Estadisticas { get; set; }
        public DbSet<Habilidad> Habilidades { get; set; }
    }
}
