//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaniaEntitiesContainer : DbContext
    {
        public TaniaEntitiesContainer()
            : base("name=TaniaEntitiesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Foto> Fotos { get; set; }
        public DbSet<Evento> Eventos { get; set; }
        public DbSet<Auspiciador> Auspiciadores { get; set; }
        public DbSet<Disciplina> Disciplinas { get; set; }
        public DbSet<Logro> Logros { get; set; }
        public DbSet<Categoria> Categorias { get; set; }
        public DbSet<Reporte> Reportes { get; set; }
        public DbSet<Estadistica> Estadisticas { get; set; }
        public DbSet<Habilidad> Habilidades { get; set; }
        public DbSet<About> Abouts { get; set; }
        public DbSet<Video> Videos { get; set; }
    }
}
